// Mock data for development - Replace with actual Supabase queries in production

export const mockBusinesses = [
  {
    id: '1',
    name: 'Kigali Marriott Hotel',
    category: 'Hotels',
    description: 'Luxury hotel in the heart of Kigali with world-class amenities and service.',
    location: 'KN 3 Ave, Kigali City Center',
    phone: '+250 788 123 456',
    website: 'https://marriott.com',
    logoUrl: 'https://logos-world.net/wp-content/uploads/2021/08/Marriott-Logo.png',
    isGsiMember: true,
    memberSince: '2024-01-15',
    overallRating: 4.8,
    totalRatings: 1248,
    categoryRatings: {
      entrance: 4.9,
      interaction: 4.7,
      heartFactor: 4.8,
      responsiveness: 4.7,
      problemResolution: 4.6,
      exit: 4.9,
    },
  },
  {
    id: '2',
    name: 'Heaven Restaurant',
    category: 'Restaurants',
    description: 'Fine dining restaurant offering a blend of international and local cuisine.',
    location: 'KG 7 Ave, Kimihurura',
    phone: '+250 788 234 567',
    website: 'https://heaven-restaurant.rw',
    logoUrl: null,
    isGsiMember: true,
    memberSince: '2023-11-20',
    overallRating: 4.7,
    totalRatings: 892,
    categoryRatings: {
      entrance: 4.8,
      interaction: 4.6,
      heartFactor: 4.7,
      responsiveness: 4.6,
      problemResolution: 4.5,
      exit: 4.8,
    },
  },
  {
    id: '3',
    name: 'Question Coffee',
    category: 'Cafés',
    description: 'Specialty coffee shop with a cozy atmosphere and excellent service.',
    location: 'KG 5 Ave, Remera',
    phone: '+250 788 345 678',
    website: 'https://questioncoffee.rw',
    logoUrl: null,
    isGsiMember: true,
    memberSince: '2024-02-10',
    overallRating: 4.6,
    totalRatings: 654,
    categoryRatings: {
      entrance: 4.7,
      interaction: 4.5,
      heartFactor: 4.6,
      responsiveness: 4.5,
      problemResolution: 4.4,
      exit: 4.7,
    },
  },
  {
    id: '4',
    name: 'Serena Hotel Kigali',
    category: 'Hotels',
    description: 'Premium hotel with exceptional views and hospitality.',
    location: 'Avenue de la Paix, Kiyovu',
    phone: '+250 788 456 789',
    website: 'https://serenahotels.com',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Serena_Hotels_logo.svg/1200px-Serena_Hotels_logo.svg.png',
    isGsiMember: true,
    memberSince: '2023-09-05',
    overallRating: 4.5,
    totalRatings: 876,
    categoryRatings: {
      entrance: 4.6,
      interaction: 4.4,
      heartFactor: 4.5,
      responsiveness: 4.5,
      problemResolution: 4.3,
      exit: 4.6,
    },
  },
  {
    id: '5',
    name: 'The Hut Restaurant',
    category: 'Restaurants',
    description: 'Local favorite serving authentic Rwandan cuisine.',
    location: 'KG 11 Ave, Remera',
    phone: '+250 788 567 890',
    website: null,
    logoUrl: null,
    isGsiMember: false,
    memberSince: null,
    overallRating: 4.4,
    totalRatings: 543,
    categoryRatings: {
      entrance: 4.5,
      interaction: 4.3,
      heartFactor: 4.4,
      responsiveness: 4.3,
      problemResolution: 4.2,
      exit: 4.5,
    },
  },
  {
    id: '6',
    name: 'Bourbon Coffee',
    category: 'Cafés',
    description: 'Rwanda\'s premier coffee brand with multiple locations.',
    location: 'KG 9 Ave, Kacyiru',
    phone: '+250 788 678 901',
    website: 'https://bourboncoffee.com',
    logoUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5xQfYxQY8Y0oQVvhxvQw-0KzWnW4nZVQhxQ&s',
    isGsiMember: true,
    memberSince: '2024-03-01',
    overallRating: 4.3,
    totalRatings: 421,
    categoryRatings: {
      entrance: 4.4,
      interaction: 4.2,
      heartFactor: 4.3,
      responsiveness: 4.2,
      problemResolution: 4.1,
      exit: 4.4,
    },
  },
]

export const mockRatings = [
  {
    id: 'r1',
    businessId: '1',
    userId: 'u1',
    userName: 'John Doe',
    entrance: 5,
    interaction: 5,
    heartFactor: 5,
    responsiveness: 4,
    problemResolution: null,
    exit: 5,
    overallRating: 4.8,
    comment: 'Excellent service from start to finish. The staff was very welcoming and professional.',
    status: 'verified' as const,
    createdAt: '2024-03-15T10:30:00Z',
  },
  {
    id: 'r2',
    businessId: '1',
    userId: 'u2',
    userName: 'Jane Smith',
    entrance: 5,
    interaction: 4,
    heartFactor: 5,
    responsiveness: 5,
    problemResolution: 5,
    exit: 5,
    overallRating: 4.8,
    comment: 'Had a minor issue with my room, but they resolved it immediately. Great customer service!',
    status: 'verified' as const,
    createdAt: '2024-03-14T15:45:00Z',
  },
  {
    id: 'r3',
    businessId: '1',
    userId: 'u3',
    userName: 'Peter Johnson',
    entrance: 4,
    interaction: 5,
    heartFactor: 4,
    responsiveness: 5,
    problemResolution: null,
    exit: 5,
    overallRating: 4.6,
    comment: 'Very good experience overall. Staff was attentive and friendly.',
    status: 'verified' as const,
    createdAt: '2024-03-13T09:20:00Z',
  },
  {
    id: 'r4',
    businessId: '2',
    userId: 'u4',
    userName: 'Alice Brown',
    entrance: 4,
    interaction: 4,
    heartFactor: 5,
    responsiveness: 4,
    problemResolution: null,
    exit: 4,
    overallRating: 4.2,
    comment: 'Nice experience, waiting for admin verification.',
    status: 'pending' as const,
    createdAt: '2024-03-16T14:20:00Z',
  },
  {
    id: 'r5',
    businessId: '3',
    userId: 'u5',
    userName: 'Bob Wilson',
    entrance: 3,
    interaction: 3,
    heartFactor: 2,
    responsiveness: 2,
    problemResolution: 1,
    exit: 2,
    overallRating: 2.2,
    comment: 'This review contains inappropriate language and is flagged for review.',
    status: 'flagged' as const,
    createdAt: '2024-03-16T16:30:00Z',
  },
  {
    id: 'r6',
    businessId: '4',
    userId: 'u6',
    userName: 'Charlie Davis',
    entrance: 5,
    interaction: 5,
    heartFactor: 5,
    responsiveness: 5,
    problemResolution: null,
    exit: 5,
    overallRating: 5.0,
    comment: 'Amazing service!',
    status: 'pending' as const,
    createdAt: '2024-03-17T09:00:00Z',
  },
]

export function getBusinessById(id: string) {
  return mockBusinesses.find((business) => business.id === id)
}

export function getRatingsByBusinessId(businessId: string) {
  return mockRatings.filter((rating) => rating.businessId === businessId)
}

export function getBusinessesByCategory(category: string) {
  if (category === 'all') return mockBusinesses
  return mockBusinesses.filter(
    (business) => business.category.toLowerCase() === category.toLowerCase()
  )
}

export function searchBusinesses(query: string) {
  const lowerQuery = query.toLowerCase()
  return mockBusinesses.filter(
    (business) =>
      business.name.toLowerCase().includes(lowerQuery) ||
      business.location?.toLowerCase().includes(lowerQuery) ||
      business.category.toLowerCase().includes(lowerQuery)
  )
}
